### ISSUE TITLE
Try to add live GUI updates during code changes

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#151]
Try to improve our quality of life by autorefreshing the GUI without restarting the application when you change the code.
I came across this, see if it would work for us (it claims to support Qt for Python so should work):
https://github.com/machinekoder/python-qt-live-coding

**Comment by rerpha** [comment]
tried this with both the main.py and the executable several different ways, didn't work. Closing this for now because it's not that much effort to restart the GUI

Here is the output of everything i tried: 
```
Traceback (most recent call last):
  File "/home/jack/.local/bin/python_qt_live_coding", line 6, in <module>
    import livecoding.gui
  File "/home/jack/.local/lib/python3.7/site-packages/livecoding/__init__.py", line 2, in <module>
    from .register_qml_types import register_types  # noqa: F401
  File "/home/jack/.local/lib/python3.7/site-packages/livecoding/register_qml_types.py", line 2, in <module>
    from python_qt_binding.QtQml import qmlRegisterType, qmlRegisterSingletonType
ImportError: cannot import name 'qmlRegisterSingletonType' from 'PySide2.QtQml' (/home/jack/.local/lib/python3.7/site-packages/PySide2/QtQml.abi3.so)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/home/jack/.local/bin/python_qt_live_coding", line 6, in <module>
    import livecoding.gui
  File "/home/jack/.local/lib/python3.7/site-packages/livecoding/__init__.py", line 2, in <module>
    from .register_qml_types import register_types  # noqa: F401
  File "/home/jack/.local/lib/python3.7/site-packages/livecoding/register_qml_types.py", line 2, in <module>
    from python_qt_binding.QtQml import qmlRegisterType, qmlRegisterSingletonType
ImportError: cannot import name 'qmlRegisterSingletonType' from 'PySide2.QtQml' (/home/jack/.local/lib/python3.7/site-packages/PySide2/QtQml.abi3.so)
```
looks like it doesnt like the qmlRegisterType function which is built into pyside2, indicating that it doesn't work for QML.
