### ISSUE TITLE
h5py error when creating a component that shares its name with a deleted component

### ISSUE THREAD

**Issue by DolicaAkelloEgwel** [ess-dmsc/nexus-constructor#283]
This is what I get...
```
Traceback (most recent call last):
  File "/home/dolica/nexus-constructor/nexus_constructor/qml_models/instrument_model.py", line 257, in add_component
    parent_group=self.instrument_group,
  File "/home/dolica/nexus-constructor/nexus_constructor/component.py", line 46, in create_component
    name, get_nx_class_for_component(component_type), parent_group
  File "/home/dolica/nexus-constructor/nexus_constructor/nexus_model.py", line 15, in create_group
    group = parent.create_group(name)
  File "/home/dolica/.local/lib/python3.6/site-packages/h5py/_hl/group.py", line 60, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl, gcpl=gcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 161, in h5py.h5g.create
ValueError: Unable to create group (name already exists)
file:///home/dolica/nexus-constructor/resources/Qtmodels/AddComponentWindow.qml:308: Error: Unable to create group (name already exists)
```

**Comment by DolicaAkelloEgwel** [comment]
@rerpha Not sure if this is a bug-bug or a result of the in-memory NeXus stuff still being work in progress?
