### ISSUE TITLE
Exception thrown when clicking on component name in main window

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#470]
the NC threw this exception when i clicked on the name of a component in the tree view in the main window: 
```
Traceback (most recent call last):
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/main_window.py", line 238, in on_clicked
    self.set_button_state()
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/main_window.py", line 212, in set_button_state
    selected_object.stored_transforms = selected_object.transforms
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/component.py", line 164, in transforms
    depends_on = self.get_field(DEPENDS_ON_STR)
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/component.py", line 99, in get_field
    return self.file.get_field_value(self.group, name)
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/nexus/nexus_wrapper.py", line 183, in get_field_value
    value = group[name][...]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/jack/.local/lib/python3.7/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "/home/jack/.local/lib/python3.7/site-packages/h5py/_hl/base.py", line 132, in _e
    name = name.encode('ascii')
AttributeError: 'ellipsis' object has no attribute 'encode'

Original exception was:
Traceback (most recent call last):
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/main_window.py", line 238, in on_clicked
    self.set_button_state()
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/main_window.py", line 212, in set_button_state
    selected_object.stored_transforms = selected_object.transforms
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/component.py", line 164, in transforms
    depends_on = self.get_field(DEPENDS_ON_STR)
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/component.py", line 99, in get_field
    return self.file.get_field_value(self.group, name)
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/nexus/nexus_wrapper.py", line 183, in get_field_value
    value = group[name][...]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/jack/.local/lib/python3.7/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "/home/jack/.local/lib/python3.7/site-packages/h5py/_hl/base.py", line 132, in _e
    name = name.encode('ascii')
AttributeError: 'ellipsis' object has no attribute 'encode'
```

To recreate: 

1. Add a component with name "test" 
2. Add a link field to component referring to /entry/sample
3. click add component 
4. click on the component's name. in the tree view

This only seems to happen sometimes, not sure what's causing it.

**Comment by rerpha** [comment]
this is an issue with the name being depends_on, closing.
