### ISSUE TITLE
Having a component with a `depends_on`, `shape` or `description` field should not be allowed 

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#473]
When clicking on a component in the treeview that has a field named `depends_on` this occurs: 

```
Traceback (most recent call last):
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/main_window.py", line 238, in on_clicked
    self.set_button_state()
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/main_window.py", line 212, in set_button_state
    selected_object.stored_transforms = selected_object.transforms
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/component.py", line 164, in transforms
    depends_on = self.get_field(DEPENDS_ON_STR)
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/component.py", line 99, in get_field
    return self.file.get_field_value(self.group, name)
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/nexus/nexus_wrapper.py", line 183, in get_field_value
    value = group[name][...]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/jack/.local/lib/python3.7/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "/home/jack/.local/lib/python3.7/site-packages/h5py/_hl/base.py", line 132, in _e
    name = name.encode('ascii')
AttributeError: 'ellipsis' object has no attribute 'encode'
``` 

Does not matter what type of field it is, if it is called `depends_on` (like in the autocompleter) it will throw this exception.

**Comment by rerpha** [comment]
We should add validation in the fields widgets that stop users from adding these fields to the component as they are bound to cause issues with other parts of the UI.
