### ISSUE TITLE
Can't recover axis direction vector for cylinders with a height of zero

### ISSUE THREAD

**Issue by DolicaAkelloEgwel** [ess-dmsc/nexus-constructor#576]
When editing a component the `axis_direction` is recovered by subtracting `base_centre` from `top_centre`. As `base_centre` and `top_centre` are products of `height`, the `axis_direction` property returns (0,0,0) when the `height` is zero. This is what is placed in the spin boxes when editing a component and if this isn't changed by the user then clicking OK leads to the following exception:

```
Traceback (most recent call last):
  File "/home/dolica/nexus-constructor/nexus_constructor/add_component_window.py", line 483, in on_ok
    component_name, description, nx_class, pixel_data
  File "/home/dolica/nexus-constructor/nexus_constructor/add_component_window.py", line 556, in edit_existing_component
    self.generate_geometry_model(self.component_to_edit, pixel_data)
  File "/home/dolica/nexus-constructor/nexus_constructor/add_component_window.py", line 422, in generate_geometry_model
    pixel_data=pixel_data,
  File "/home/dolica/nexus-constructor/nexus_constructor/component/component.py", line 325, in set_cylinder_shape
    validate_nonzero_qvector(axis_direction)
  File "/home/dolica/nexus-constructor/nexus_constructor/geometry/utils.py", line 7, in validate_nonzero_qvector
    raise ValueError("Vector is zero length")
ValueError: Vector is zero length
```

**Comment by mattclarke** [comment]
Don't allow 0!
