### ISSUE TITLE
Renaming a translation causes errors

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#619]
even if not depended on this causes issues as the view (and model?) do not get updated so are still pointing at deleted references in the nexus file. 

exception: 
```
Traceback (most recent call last):
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/main_window.py", line 337, in _update_transformations_3d_view
    self.sceneWidget.add_transformation(component.name, component.transform)
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/component/component.py", line 194, in transform
    for transform in self.transforms_full_chain:
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/component/component.py", line 155, in transforms_full_chain
    self._get_transform(depends_on, transforms)
  File "/home/jack/code/repos/nexus-constructor/nexus_constructor/component/component.py", line 171, in _get_transform
    transform_dataset = self.file.nexus_file[depends_on]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'Translation' doesn't exist)"
```

**Comment by rerpha** [comment]
ok, this is to do with a `dependee_of` not updating its `depends_on` attribute when the transformation is renamed.
